services:
  indexer-postgres:
    image: postgres:14-alpine
    container_name: starterkit-indexer-postgres
    profiles:
      - indexer-db
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $INDEXER_POSTGRES_USER -d $INDEXER_POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ../data/indexer/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${INDEXER_POSTGRES_PASSWORD}
      - POSTGRES_USER=${INDEXER_POSTGRES_USER}
      - POSTGRES_DB=${INDEXER_POSTGRES_DB}
    networks:
      - indexer-db-net
    restart: unless-stopped

networks:
  indexer-db-net: