services:
  indexer-postgres:
    image: postgres:14-alpine
    container_name: starterkit-indexer-postgres
    profiles:
      - indexer
      - indexer-db
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $INDEXER_POSTGRES_USER -d $INDEXER_POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ../data/indexer/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${INDEXER_POSTGRES_PASSWORD}
      - POSTGRES_USER=${INDEXER_POSTGRES_USER}
      - POSTGRES_DB=${INDEXER_POSTGRES_DB}
    networks:
      - indexer-net
    restart: unless-stopped

  indexer:
    image: starterkit-chain-base
    build:
      dockerfile: ./docker/base/Dockerfile
      context: ../..
    container_name: starterkit-indexer
    environment:
      - INDEXER_DATABASE_URL=${INDEXER_DATABASE_URL}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - PROTOKIT_SHOULD_ATTEMPT_INDEXER_DB_MIGRATION=${PROTOKIT_SHOULD_ATTEMPT_INDEXER_DB_MIGRATION}
      - PROTOKIT_LOG_LEVEL=${PROTOKIT_LOG_LEVEL}
      - PROTOKIT_INDEXER_GRAPHQL_HOST=${PROTOKIT_INDEXER_GRAPHQL_HOST}
      - PROTOKIT_INDEXER_GRAPHQL_PORT=${PROTOKIT_INDEXER_GRAPHQL_PORT}
      - INDEXER_OPEN_TELEMETRY_METRICS_HOST=${INDEXER_OPEN_TELEMETRY_METRICS_HOST}
      - INDEXER_OPEN_TELEMETRY_METRICS_PORT=${INDEXER_OPEN_TELEMETRY_METRICS_PORT}
    profiles:
      - indexer
    depends_on:
      indexer-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget http://${PROTOKIT_INDEXER_GRAPHQL_HOST}:${PROTOKIT_INDEXER_GRAPHQL_PORT}/graphql",
        ]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - indexer-net
      - routing-net
      - queue-net
    ports:
      - 8081:${PROTOKIT_INDEXER_GRAPHQL_PORT}
    command:
      [
        "./dist/start.js start ./core/environments/${PROTOKIT_ENV_FOLDER}/indexer.config.js",
      ]
    labels:
      logging: "promtail"
      logging_jobname: "indexer"

networks:
  indexer-net:
