services:
  processor-postgres:
    image: postgres:14-alpine
    container_name: starterkit-processor-postgres
    profiles:
      - processor
      - processor-db
    ports:
      - "127.0.0.1:5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $PROCESSOR_POSTGRES_USER -d $PROCESSOR_POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ../data/processor/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PROCESSOR_POSTGRES_PASSWORD}
      - POSTGRES_USER=${PROCESSOR_POSTGRES_USER}
      - POSTGRES_DB=${PROCESSOR_POSTGRES_DB}
    networks:
      - processor-net
    restart: unless-stopped

  processor:
    image: starterkit-chain-base
    build:
      dockerfile: ./docker/base/Dockerfile
      context: ../..
    container_name: starterkit-processor
    environment:
      - PROCESSOR_DATABASE_URL=${PROCESSOR_DATABASE_URL}
      - PROTOKIT_SHOULD_ATTEMPT_PROCESSOR_DB_MIGRATION=${PROTOKIT_SHOULD_ATTEMPT_PROCESSOR_DB_MIGRATION}
      - PROTOKIT_LOG_LEVEL=${PROTOKIT_LOG_LEVEL}
      - PROTOKIT_PROCESSOR_GRAPHQL_HOST=${PROTOKIT_PROCESSOR_GRAPHQL_HOST}
      - PROTOKIT_PROCESSOR_GRAPHQL_PORT=${PROTOKIT_PROCESSOR_GRAPHQL_PORT}
      - PROTOKIT_PROCESSOR_INDEXER_GRAPHQL_HOST=${PROTOKIT_PROCESSOR_INDEXER_GRAPHQL_HOST}
      - PROTOKIT_INDEXER_GRAPHQL_PORT=${PROTOKIT_INDEXER_GRAPHQL_PORT}
    profiles:
      - processor
    depends_on:
      processor-postgres:
        condition: service_healthy
      indexer:
        condition: service_healthy
    networks:
      - processor-net
      - indexer-net
      - routing-net
    ports:
      - 8082:${PROTOKIT_PROCESSOR_GRAPHQL_PORT}
    working_dir: /app
    command: ["./dist/start.js start ./core/environments/${PROTOKIT_ENV_FOLDER}/processor.config.js",]
    labels:
      logging: "promtail"
      logging_jobname: "processor"

networks:
  processor-net:
