version: "3.9"

services:
  api_server:
    build:
      context: ../../
      dockerfile: docker/chain/Dockerfile
    command: sh -c "pnpm start-server"
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.api_server.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.api_server.entrypoints=websecure"
      - "traefik.http.routers.api_server.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.api_server.middlewares=SslHeader@file"

networks:
  proxy-network:
    external: true
