services:
  worker:
    extends:
      file: ./worker-template.yml
      service: worker-base
    container_name: starterkit-worker
    environment:
      - PROTOKIT_WORKER_VARIANT=${PROTOKIT_WORKER_VARIANT}

  worker-2:
    extends:
      file: ./worker-template.yml
      service: worker-base
    container_name: starterkit-worker-2
    environment:
      - PROTOKIT_WORKER_VARIANT=${PROTOKIT_WORKER_VARIANT_2}

  worker-3:
    extends:
      file: ./worker-template.yml
      service: worker-base
    container_name: starterkit-worker-3
    environment:
      - PROTOKIT_WORKER_VARIANT=${PROTOKIT_WORKER_VARIANT_3}

  worker-4:
    extends:
      file: ./worker-template.yml
      service: worker-base
    container_name: starterkit-worker-4
    environment:
      - PROTOKIT_WORKER_VARIANT=${PROTOKIT_WORKER_VARIANT_4}
