services:
  worker:
    extends:
      file: ./worker-template.yml
      service: worker-base
    container_name: starterkit-worker
    profiles:
      - worker-monolithic
    environment:
      - PROTOKIT_WORKER_VARIANT=default

  worker-1:
    extends:
      file: ./worker-template.yml
      service: worker-specialized-base
    container_name: starterkit-worker-1
    environment:
      - PROTOKIT_WORKER_VARIANT=l1

  worker-2:
    extends:
      file: ./worker-template.yml
      service: worker-specialized-base
    container_name: starterkit-worker-2
    environment:
      - PROTOKIT_WORKER_VARIANT=st

  worker-3:
    extends:
      file: ./worker-template.yml
      service: worker-specialized-base
    container_name: starterkit-worker-3
    environment:
      - PROTOKIT_WORKER_VARIANT=transaction

  worker-4:
    extends:
      file: ./worker-template.yml
      service: worker-specialized-base
    container_name: starterkit-worker-4
    environment:
      - PROTOKIT_WORKER_VARIANT=block
