version: "3.9"

services:
  worker:
    image: starterkit-sequencer
    build:
      dockerfile: ./docker/base/Dockerfile
      context: ../..
    container_name: starterkit-worker
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
    profiles:
      - worker
    depends_on:
      - redis
    networks:
      - db-net
    command: ["${INDEX_JS}", "${PROTOKIT_ENV}", "${WORKER_CONFIG}"]
